// Generated by CoffeeScript 1.6.3
$(document).ready(function(){
	
   //test(path);
   //$("#svgImg g:last-child").append("<path class='123' fill='red' stroke='red' stroke-miterlimit='10' d='M32.756,358.034c69.748-57.143,177.311-79.832,264.884-57.143'/>");
   
})
	function f2(path){
   	   
   	   /*$('#svgImg path#xinjiang').fadeIn(2000,function(){
   	   	   $('#svgImg path#xinjiang').attr({fill:"#5dc578",stroke:"none"});
   	   })*/
   	   $(path).fadeIn(2000,function(){
   	   	   $(path).attr({fill:"#46D3C2",stroke:"none"});
   	   	   $(".svgtext").attr("fill","#fff");
   	   	   $(".beijingtext").attr("fill","#e5500e");
   	   	   $(".blacktext").attr("fill","#333");
   	   	   
   	   	   
				$("path").hover(
				function(){
					
					if(!$(this).hasClass("hover")){
						$(this).get(0).setAttribute("class","hover");
						for(var i in mapConfig){
							if(i==$(this).attr("id")){
								$(this).attr("transform","translate(-1,-1)");
								$(this).attr({fill:"#5dc578",stroke:"none"});
							}
						}
						
					}
				},
				function(){
					$(this).attr("class","");
					for(var i in mapConfig){
							if(i==$(this).attr("id")){
								$(this).attr("transform","");
								$(this).attr({fill:"#46D3C2",stroke:"none"});
							}
						}
					
				})
		  
   	   	  
           
   	   })
   	   	   
   	 
   }
	
function test(path){

	 var length = path.getTotalLength();
    // 清除之前的动作
    path.style.transition = path.style.WebkitTransition ='none';
    // 设置起始点
    path.style.strokeDasharray = length + ' ' + length;
    path.style.strokeDashoffset = length;
    // 获取一个区域，获取相关的样式，让浏览器寻找一个起始点。
    path.getBoundingClientRect();
    // 定义动作
    path.style.transition = path.style.WebkitTransition =
    'stroke-dashoffset 3s linear';
    // Go!
    path.style.strokeDashoffset = '0';
   setTimeout(f2(path),3*1000);

}